---
- name: make a build dir
  file: state=directory name=/root/hbase-regionserver-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/hbase-regionserver-dockerized/Dockerfile

- name: put run
  template: src=run dest=/root/hbase-regionserver-dockerized/run mode=0755

- name: build a Docker image for HBase regionserver
  command: docker build -t gitinsky/hbase-regionserver:0.1.0 --rm /root/hbase-regionserver-dockerized

- name: tag it as latest
  command: docker build -t gitinsky/hbase-regionserver:latest --rm /root/hbase-regionserver-dockerized
